=== N3BUL0S4/2Daw_23-24/Ejercicios/Lenguaje_de_marcas/XML/Hoja4/4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="periodico">
        <xs:sequence>
            <xs:element name="articulo" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titular" type="xs:string"/>
                        <xs:element name="subtitulo" type="xs:string" minOccurs="0"/>
                        <xs:element name="cuerpo" type="xs:string"/>
                        <xs:element name="autores" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="fecha" type="xs:date" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="periodico" type="periodico"></xs:element>
</xs:schema>

=== N3BUL0S4/2Daw_23-24/Ejercicios/Lenguaje de marcas/XML/Hoja4/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<periodico xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="4.xsd">
    <articulo fecha="2000-02-02">
        <titular>a</titular>
        <cuerpo>a</cuerpo>
        <autores>a</autores>
    </articulo>
    <articulo>
        <titular>b</titular>
        <cuerpo>b</cuerpo>
        <autores>b</autores>
        <autores>c</autores>
    </articulo>
</periodico>
