=== N3BUL0S4/2Daw_23-24/Ejercicios/Lenguaje de marcas/Examen/EJE_03/agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fichas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                            <xs:element name="apellido1" type="xs:string"/>
                            <xs:element name="apellido2" type="xs:string" minOccurs="0"/>
                            <xs:element name="telefonosNacio">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="telefono" type="telefonoNac" maxOccurs="5" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="tipo" type="tipotelefono"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="telefonosInter">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="telefono" type="telefonoInter" minOccurs="0" maxOccurs="2"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="emails">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email" type="email" minOccurs="0" maxOccurs="2"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="direciones_postales">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direcon_postal" type="direccion_postal"  minOccurs="0" maxOccurs="3"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="categoria" type="categoria" use="required"/>
                        <xs:attribute name="zona" type="zona" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="zona">
        <xs:restriction base="xs:string">
            <xs:enumeration value="La flota"/>
            <xs:enumeration value="Infante"/>
            <xs:enumeration value="San Anton"/>
            <xs:enumeration value="Ronda Norte"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="categoria">
        <xs:restriction base="xs:string">
            <xs:enumeration value="empresa"/>
            <xs:enumeration value="particular"/>
            <xs:enumeration value="comercial"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="direccion_postal">
        <xs:sequence>
            <xs:element name="Calle" type="xs:string"/>
            <xs:element name="piso" type="xs:string" minOccurs="0"/>
            <xs:element name="letra" type="xs:string" minOccurs="0"/>
            <xs:element name="codigo_postal" type="codigo_postal"/>
            <xs:element name="ciudad" type="xs:string"/>
            <xs:element name="Pais"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="codigo_postal">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9.]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefonoInter">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+\d{2} \d{9}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefonoNac">
        <xs:restriction base="xs:string">
            <xs:pattern value="[6-9]\d{8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipotelefono">
        <xs:restriction base="xs:string">
            <xs:enumeration value="movil"/>
            <xs:enumeration value="fijo"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== N3BUL0S4/2Daw_23-24/Ejercicios/Lenguaje de marcas/Examen/EJE_03/agenda.xml
<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="agenda.xsd">
    <ficha categoria="empresa">
        <Nombre>Jose Luis</Nombre>
        <apellido1>Domingez</apellido1>
        <apellido2>Rodrigez</apellido2>
        <telefonosNacio>
            <telefono>987654321</telefono>
            <telefono>891372319</telefono>
            <telefono>789723493</telefono>
            <telefono>612389763</telefono>
            <telefono>613209473</telefono>
        </telefonosNacio>
        <telefonosInter>
            <telefono>+23 987654321</telefono>
            <telefono>+34 235798234</telefono>
        </telefonosInter>
        <emails>
            <email>Joseluis123@asdfa.com</email>
            <email>Joseluis321@asdfa.com</email>
        </emails>
        <direciones_postales>
            <direcon_postal>
                <Calle>Domingas</Calle>
                <codigo_postal>99999</codigo_postal>
                <ciudad>Pliego</ciudad>
                <Pais>Carabanchel</Pais>
            </direcon_postal>
            <direcon_postal>
                <Calle>Domingos</Calle>
                <codigo_postal>13123</codigo_postal>
                <ciudad>Calasparra</ciudad>
                <Pais>Kazagistan</Pais>
            </direcon_postal>
        </direciones_postales>
    </ficha>
    <ficha categoria="particular">
        <Nombre>Paco</Nombre>
        <apellido1>Prieto</apellido1>
        <telefonosNacio></telefonosNacio>
        <telefonosInter></telefonosInter>
        <emails></emails>
        <direciones_postales></direciones_postales>
    </ficha>
    <ficha categoria="comercial">
        <Nombre>Antonio</Nombre>
        <apellido1>A</apellido1>
        <apellido2>B</apellido2>
        <telefonosNacio>
            <telefono>609237098</telefono>
        </telefonosNacio>
        <telefonosInter></telefonosInter>
        <emails>
            <email>Antonioprito123@gmail.com</email>
        </emails>
        <direciones_postales></direciones_postales>
    </ficha>
    <ficha categoria="particular">
        <Nombre>Faustino</Nombre>
        <apellido1>Marrano</apellido1>
        <telefonosNacio></telefonosNacio>
        <telefonosInter>
            <telefono>+12 145908792</telefono>
        </telefonosInter>
        <emails></emails>
        <direciones_postales>
            <direcon_postal>
                <Calle>Pajaritas de las nieves</Calle>
                <codigo_postal>12345</codigo_postal>
                <ciudad>Banglades</ciudad>
                <Pais>Malasia</Pais>
            </direcon_postal>
        </direciones_postales>
    </ficha>
</fichas>
