<!DOCTYPE mensajes [
    <!ELEMENT mensajes (mensaje+)>
    <!ELEMENT mensaje (telefono, fecha, hora, contenido)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT hora (#PCDATA)>
    <!ATTLIST hora zonaHoraria CDATA #REQUIRED>
    <!ELEMENT contenido (#PCDATA)>
]>

<mensajes>
    <mensaje>
        <telefono>123456789</telefono>
        <fecha>11/11/1111</fecha>
        <hora zonaHoraria="+1:00">1:11</hora>
        <contenido>Contenido1</contenido>
    </mensaje>
    <mensaje>
        <telefono>987654321</telefono>
        <fecha>22/22/2222</fecha>
        <hora zonaHoraria="-7:00">2:22</hora>
        <contenido>Contenido2</contenido>
    </mensaje>
</mensajes>